# Site settings
title: Your awesome title
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://teorojas.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: TeoRojas

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1
    span:
      line_numbers: false
  syntax_highlighter: rouge

# Theme and Build settings
theme: minima
plugins:
  - jekyll-feed

# Markdown extensions (optional: requires pymdown-extensions installed)
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Exclude settings
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include specific files if needed
include:
  - README.md
  - LICENSE.md
